all_in_one_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog_app.views import Home, Index, Contact, School, Pay,Faq,Pp,Terms,Services,Ebook,Aboutmore
from django.conf.urls.static import static
from django.conf import settings
from main.views import module_detail


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", Index.as_view(), name="index"),
    path("school", School.as_view(), name="school"),
    path("home/", Home.as_view(), name="home"),
    path("faq/", Faq.as_view(), name="faq"),
    path("pp/", Pp.as_view(), name="pp"),
    path("services/", Services.as_view(), name="services"),
    path("aboutmore/", Aboutmore.as_view(), name="aboutmore"),
    path("ebook/", Ebook.as_view(), name="ebook"),
    path("terms/", Terms.as_view(), name="terms"),
    path("contact/", Contact.as_view(), name="contact"),
    path("pay/",Pay.as_view(), name="pay"),
    path("blog/", include("blog_app.urls")),
    path("account/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("quiz/", include("quiz.urls", namespace='quiz')),
    path("main/", include("main.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('module_detail/<int:module_id>/', module_detail, name='module_detail'),
] 

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler404 = 'main.views.error_404'

main/urls.py
from django.urls import path
from main import views 


urlpatterns = [
    path('courses/', views.courses, name='courses'),
    path('about/', views.about, name='about'),
    path('pay/', views.pay, name='pay'),
    path('dashboard/home/', views.dashboard_home, name='dashboard-home'),
    path('dashboard/profile/', views.profile, name='profile'),
    path('dashboard/courses-enrolled/', views.courses_enrolled, name='courses-enrolled'),
    path('dashboard/courses-uploaded/', views.courses_uploaded, name='courses-uploaded'),
    path('dashboard/upload/', views.upload, name='upload'),
    path('dashboard/<slug:slug>/course-edit/', views.course_edit, name='course-edit'),
    path('dashboard/<slug:slug>/delete/', views.delete_course, name='delete-course'),
    path('<str:instructor>/course/<slug:slug>/', views.course_details, name='course_details'),
    path('courses/<str:category>/', views.category, name='category'),
    path('module_detail/<int:module_id>/', views.module_detail, name='module_detail'),
    path('dash/<int:course_id>/', views.dash, name='dash'),
    path('dash/', views.dash, name='dash_no_id'),
    path('error_404/', views.error_404, name='error_404'),
    path('course/<int:course_id>/', views.course_details, name='course_details'),


    path('dash/<int:course_id>/', views.redirect_dash, name='redirect_dash'),
    path('dash/', views.redirect_dash_no_id, name='redirect_dash_no_id'),
    path('dashboard/', views.dash, name='dash'),

]

quiz/urls.py
from django.urls import path
from .views import (
    QuizListView,
    quiz_view,
    quiz_data_view,
    save_quiz_view,)

app_name= 'quiz'


urlpatterns = [
    # path('main/<int:course_id>/', QuizListView.as_view(), name='main'),
    path('main/', QuizListView.as_view(), name='main'),
    path('main/<int:pk>/', quiz_view, name='quiz_view'),
    path('main/<int:pk>/save/', save_quiz_view, name='save_view'),
    path('main/<int:pk>/data/', quiz_data_view, name='quiz_data_view'),
]

quiz/models.py
from django.db import models
from django.contrib.auth.models import User
from main.models import Module,Course
import random


from django.utils import timezone
import uuid







DIFF_CHOICES = (
    ('Easy', 'Easy'),
    ('Medium', 'Medium'),
    ('Hard', 'Hard')
)

class Quiz(models.Model):
    name = models.CharField(max_length=255)
    topic = models.CharField(max_length=255)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="Duration of the quiz in minutes")
    score_to_pass = models.IntegerField(help_text="Score in %")
    difficulty = models.CharField(max_length=6, choices=DIFF_CHOICES)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='quiz_course')
    module = models.ForeignKey(Module, on_delete=models.CASCADE, related_name='quiz_module')
    is_completed = models.BooleanField(default=False)  # New field to track quiz completion

    def __str__(self):
        return f"{self.name}-{self.topic}"
    
    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]
    
    class Meta:
        verbose_name_plural = "Quizzes"

class Question(models.Model):
    text = models.CharField(max_length=255)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.text)
    
    def get_answers(self):
        return self.answer_set.all()


class Answer(models.Model):
    text = models.CharField(max_length=255)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"question: {self.question.text}, answer: {self.text}, correct: {self.correct} "
     

class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()
    
    def __str__(self):
        return str(self.pk)

templates/school/about.html
{% extends 'base_main.html' %}
{% load static %}
{% block content %}

  <main id="main">
    <section class="about_us">
      <div class="container">            
          <div class="row">
              <div class="col-12 col-sm-12 col-md-7 col-lg-7">
                  <div class="about_title">
                      <span></span><h2>About Us</h2><br>
                     
                      <p style="text-align: justify;">Keres Engineering and Appliance Technology (KEAT) is a Zambian registered engineering company, established under Act No. 16 of 2011 of the Laws of Zambia. KEAT is dedicated to providing specialized, professional, and high-quality electrical engineering and appliance repair services to its valued customers, both locally and internationally. We are passionate about equipping individuals with the skills needed in various engineering fields through our comprehensive Continuous Professional Development (CPD) courses.

                        CPD is a continuous and ongoing process of acquiring new skills, knowledge, and competencies throughout one’s lifetime. It should be a personal commitment for every professional or individual to stay up to date with the latest developments, adapt to changes, and continuously improve their skills. At KEAT, we believe that growth in knowledge leads to growth in life and global development.
                        
                        At KEAT, we are committed to providing specialized and quality services in the electrical and Appliance technological fields. Furthermore , we are fostering a skilled, equipped, and effective workforce, ensuring that positive change is inevitable around us.</p>
                      {% comment %} <a href="{% url 'aboutmore' %}" title="">Read More About Us <i class="fas fa-angle-right"></i></a> {% endcomment %}
                   </div>
              </div>
              <div class="col-12 col-sm-12 col-md-5 col-lg-5 p-0">
                  <div class="banner_about">
                    <img src="{% static 'edulook/images/about/about.jpg' %}" alt="Image" class="phone-1" data-aos="fade-right" style="height:500px; width:500px;">
                   </div>
              </div>
              <div class="row about_content_wrapper">
            <div class="col-12 col-sm-12 col-md-7 col-lg-7">
                <div class="about_content">
                    <h2>Brief History </h2>
                    <p style="text-align: justify;">Keres Engineering and Appliance Technology (KEAT) was established in 2022 with a primary focus on providing specialized sewing machine repair services. Originating from a background in industrial maintenance supervision at a leading company, KEAT quickly gained recognition for its commitment to quality and excellence in repair services.<br><br>
  
                      Over time, driven by a growing demand for broader engineering solutions, KEAT expanded its offerings to include comprehensive electrical engineering services and diversified appliance repairs. Today, KEAT stands as a trusted provider of appliance repair services, specializing in a wide range of household appliances.<br><br>
                      
                      In addition to our repair expertise, KEAT is dedicated to enhancing professional development within the engineering community through our Continuous Professional Development (CPD) courses. These courses are designed to equip individuals with the skills necessary to excel in various engineering fields, ensuring they remain at the forefront of industry advancements.<br><br>
                      
                      From humble beginnings in the sewing machine repair industry to a multifaceted engineering and appliance technology company, KEAT continues to uphold its core values of excellence, innovation, and community impact. Our journey reflects our unwavering dedication to delivering reliable, high-quality services and empowering individuals through education and training.<br><br></p>
                </div>
            </div>
          </div>        
         
      </div>  
  </section>
  
  
  <!--========={ Popular Courses }========-->
  <section class="unlimited_possibilities" id="about_unlimited_possibilities">
      <div class="container">
          <div class="row">
              <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                  <div class="sub_title">
                      <h2>We pride ourselves in deivering quality services always </h2>
                  </div><!-- ends: .section-header -->
              </div>
              
              <div class="col-12 col-sm-6 col-md-4 col-lg-4">
                   <div class="single_item single_item_first">
                      <div class="icon_wrapper">
                          <i class="flaticon-student"></i>
                      </div>
                      <div class="accordion accordion-flush " id="accordionFlushExample">
                        <div class="accordion-item">
                          <h2 class="accordion-header" id="flush-headingTwo">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                             <b>Our Mission</b>
                            </button>
                          </h2>
                          <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
                            <div class="accordion-body"> 
                             <p style="text-align: justify;">
                             To empower communities by providing reliable appliance repair and electrical services, manufacturing affordable, high-quality appliances, and offering comprehensive appliance repair training courses to foster skill development and economic empowerment.</p>                    
                                  </p>  </div>
                          </div>
                        </div>
                      </div> 
                        
                  </div>
              </div>
              <div class="col-12 col-sm-6 col-md-4 col-lg-4">
                  <div class="single_item single_item_center">
                      <div class="icon_wrapper">
                          <i class="flaticon-university"></i>
                      </div>
                      <div class="accordion accordion-flush " id="accordionFlushExample">
                        <div class="accordion-item">
                          <h2 class="accordion-header" id="flush-headingOne">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                             <b>Our Vision</b>
                            </button>
                          </h2>
                          <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                            <div class="accordion-body"> 
                             <p style="text-align: justify;">
                              To revolutionize the appliance and electrical industry by becoming a leading provider of innovative, sustainable, and accessible appliance and electrical solutions that enhance everyday living and contribute to societal progress.        
                                  </p>  </div>
                          </div>
                        </div>
                      </div> 
                      
                  </div>
              </div>
                         
              <div class="col-12 col-sm-6 col-md-4 col-lg-4">
                   <div class="single_item single_item_center">
                      <div class="icon_wrapper">
                          <i class="flaticon-atom"></i>
                      </div>
                      <div class="accordion accordion-flush " id="accordionFlushExample">
                        <div class="accordion-item">
                          <h2 class="accordion-header" id="flush-headingThree">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                             <b>Core Values</b>
                            </button>
                          </h2>
                          <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
                            <div class="accordion-body"> 
                             <p style="text-align: left;">
                             <b> 1. Excellence:</b> We strive for excellence in all that we do, delivering exceptional products, services, and training programs.<br>
                              <b>2. Innovation:</b> We embrace innovation, continuously seeking new ways to improve our products, services, and training methods.<br>
                             <b> 3. Community Impact:</b> We are dedicated to making a positive impact in our communities by providing valuable services and opportunities for skill development.<br>
                             <b> 4. Integrity:</b> We conduct ourselves with integrity, honesty, and transparency in all our dealings with customers, partners, and stakeholders.<br>
                             <b> 5. Sustainability:</b> We are committed to sustainability, considering environmental and social factors in our business decisions and practices</p>  </div>
                          </div>
                        </div>
                      </div>   
                  </div>
              </div>          
          </div>
      </div>
  </section><!-- End Popular Courses -->


  </main><!-- End #main -->

{% endblock %}

templates/school/access_course.html
<!-- access_course.html -->

{% extends 'school/base.html' %}

{% block content %}
  <h2>{{ course.title }}</h2>
  <p>{{ course.description }}</p>

  {% for module in modules %}
    <h3>{{ module.title }}</h3>
    <p>{{ module.content }}</p>

    {% if not forloop.first %}
      <!-- Link to previous module -->
      <a href="{% url 'module_detail' instructor=course.instructor.username course_slug=course.slug module_id=modules|slice:":forloop.counter0:forloop.counter|add:"-2"|last %}">Previous Module</a>
    {% endif %}

    {% if not forloop.last %}
      <!-- Link to next module -->
      <a href="{% url 'module_detail' instructor=course.instructor.username course_slug=course.slug module_id=module.id %}">Next Module</a>
    {% endif %}
  {% endfor %}
{% endblock %}

templates/school/category.html
{% extends 'base_main.html' %}
{% load static %}
{% block title %}{{ category }}{% endblock title %}
{% block content %}

<section  class="section" style="width: 100%; height: 380px; overflow: hidden;background: #2d71a1; background: linear-gradient(-45deg, #274685, #1391a5); color: #fff; box-shadow: 0 10px 30px 0 rgba(0, 0, 0, 0.15);">
  <div class="row justify-content-center">
    <div class="col-md-10 p-0">
      <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
        <div class="carousel-inner" style="box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);">
          <div class="carousel-item active">
            <div class="card-1" style="width: 100%; height: 334px; padding: 20px;">
              <img src="{% static 'panel/assets/img/slide-1.png' %}" class="card-img-top" alt="...">
            </div>
          </div>
          <div class="carousel-item">
            <div class="card-1" style="width: 100%; height: 334px; padding: 20px;">
              <img src="{% static 'panel/assets/img/slide-1.png' %}" class="card-img-top" alt="...">
            </div>
          </div>
          <div class="carousel-item">
            <div class="card-1" style="width: 100%; height: 334px; padding: 20px;">
              <img src="{% static 'panel/assets/img/slide-3.png' %}" class="card-img-top" alt="...">
            </div>
          </div>
        </div>
      </div>

      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
        {% comment %} <span class="carousel-control-prev-icon" aria-hidden="true"></span> {% endcomment %}
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
        {% comment %} <span class="carousel-control-next-icon" aria-hidden="true"></span> {% endcomment %}
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</section>

<main id="main" class="main">
  <div class="container">
    <br>
   <div class="pagetitle">
    <h5 class="card-title">Category: {{ category }}</h5>
   </div>
<br>
<hr>

  {% if courses %}
 <div class="row align-items-top">
  {% for course in courses|slice:6 %}
  <div class="col-lg-3">
 <div class="card">
  <img src="{{course.thumbnail.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"><a href="{% url 'course_details' instructor=course.instructor slug=course.slug %}">{{ course.title|slice:":80" }}</a></h5>
    <span class="badge bg-dark"><i class="bi bi-info-circle me-1">Level</i>: {{ course.level }}</span>
    <span class="badge bg-dark"><i class="bi bi-info-circle me-1"> Duration</i>: {{ course.duration }}</span>
    <a href="{% url 'course_details' instructor=course.instructor slug=course.slug %}" > <button type="button" class="btn btn-outline-secondary"style="background: #2d71a1; background: linear-gradient(-45deg, #1391a5, #274685); color: #fff; box-shadow: 0 10px 30px 0 rgba(0, 0, 0, 0.15);" >View More</button></a>
  </div>
</div>
   </div>
   {% endfor %}
   {% else %}
   <div class="col-md-12">
     <p style='margin: 2rem 0;'>No courses found in this category.</p>
   </div>
 {% endif %}
    </div>

 </div>
 </main><!-- End #main -->
{% endblock %}

templates/school/contact.html
{% extends 'school/base.html' %}
{% load static %}


{% block title %}Contact{% endblock title %}

{% block content %}

<section class="contact">
    <div class="container contact-content">
        <h2>Get in touch.</h2>
        <p style="margin: 1rem 0;" >We are always ready to hear your feedbacks & queries. Our average response time is 30 minutes.</p>
        <div class="contact-container">
            <div class="contact-img">
                <img src='{% static 'img/contact-img.webp' %}'>
            </div>
            <form class="contact-form" method="post" action="/contact/">
                {% csrf_token %}
                <div>
                    <label for="firstname">Name</label>
                    <input placeholder='John' type="text" id="firstname" name="firstname">
                </div>
                <div>
                    <label for="email">Email</label>
                    <input placeholder='example@gmail.com' type="text" id="email" name="email">
                </div>
                <div>
                    <label for="phone">Phone</label>
                    <input placeholder='xxx xxx xxxx' type="text" id="phone" name="phone">
                </div>
                <div>
                    <label for="message">Message</label>
                    <textarea id="message" placeholder="your message..."></textarea>
                </div>
                <div>
                    <button id="submit-button" type='submit'>Send</button>
                </div>
            </form>
        </div>
    </div>
</section>

{% endblock content %}

templates/school/course_details copy.html
<!-- course_details.html -->
{% extends 'school/base.html' %}

{% block content %}
  <h1>{{ course.title }}</h1>
  <p>{{ course.description }}</p>

  <!-- Existing course details content -->

  <!-- Modules -->
  <h2>Modules</h2>
  <ul>
    {% for module in course.module_set.all %}
      <li>{{ module.title }} - {{ module.description }}
        <a href="{% url 'edit_module' instructor=course.instructor.username slug=course.slug module_id=module.id %}">Edit</a>
        <a href="{% url 'delete_module' instructor=course.instructor.username slug=course.slug module_id=module.id %}">Delete</a>
      </li>
      <ul>
        {% for quiz in module.quiz_set.all %}
          <li>{{ quiz.question }} - Correct Option: {{ quiz.correct_option }}
            <a href="{% url 'edit_quiz' instructor=course.instructor.username slug=course.slug quiz_id=quiz.id %}">Edit</a>
            <a href="{% url 'delete_quiz' instructor=course.instructor.username slug=course.slug quiz_id=quiz.id %}">Delete</a>
          </li>
        {% endfor %}
        <li><a href="{% url 'add_quiz' instructor=course.instructor.username slug=course.slug module_id=module.id %}">Add Quiz</a></li>
      </ul>
    {% endfor %}
    <li><a href="{% url 'add_module' instructor=course.instructor.username slug=course.slug %}">Add Module</a></li>
  </ul>
{% endblock %}

templates/school/courses.html
{% extends 'school/base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}

<section class="">
    <div class="container">
        <h2 style='font-size: 1.5rem;'>Courses</h2>
        <div class="courses">
            {% for course in courses %}
<div class="course">
    <div class="course-thumbnail">
        <a href="{% url 'course_details' instructor=course.instructor slug=course.slug %}">
            <img src='{{course.thumbnail.url}}'>
        </a>
    </div>
    <div class="course-details">
        <a href="{% url 'course_details' instructor=course.instructor slug=course.slug %}"><h3>{{ course.title|slice:":80" }}</h3></a>
        <p style="display: inline-flex; column-gap: 1rem; justify-content: center; align-items: center;" class="instructor">
            <img class="instructor-img" src="https://api.dicebear.com/5.x/shapes/svg?seed={{ course.instructor }}">
            Instructor: {{ course.instructor }}
        </p>
        <p class="course-desc">{{ course.description|slice:":100" }}</p>
        <p class="course-lvl-time">
            {{ course.level }} &middot; {{ course.duration }} Hours
        </p>
        <a href="{% url 'course_details' instructor=course.instructor slug=course.slug %}" class="btn enroll-btn">Enroll now</a>
    </div>
</div>
{% endfor %}
        </div>
    </div>
</section>

{% endblock content %}

templates/school/module_detail.html
{% extends 'panel/base.html' %}

{% load static %}
{% block title %}module_detail{% endblock title %}



{% block scripts %}
{% comment %} <script src="{% static 'quiz/jquery-3.7.1.js' %}"></script> {% endcomment %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'quiz/main.js' %}" defer></script>
{% endblock %}


{% block content %}
{% comment %} <main id="main" class="main-dark">
    <div class="pagetitle">
      <h1>{{ module.title }}</h1>
    </div><!-- End Page Title -->
    <section class="section">
      <div class="row">
        <div class="col-lg-12">
          <div class="modal fade" id="QuizModal" tabindex="-1">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Start?</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="modal-body-confirm">
                  <p> You will be redirected </p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-danger" data-bs-dismiss="modal">no</button>
                  <button class="btn btn-success" id="start-button" type="submit" class="btn btn-outline-secondary" >yes</button>
                </div>
              </div>
            </div>
          </div>
   {% endcomment %}

  <main id="main" class="main">
    <div class="pagetitle">
      <h1>{{ module.title }}</h1>
    </div><!-- End Page Title -->
    <div class="container">
    <section class="section">
      <div class="row">
          <div class="card">
            <div class="card-body">
                <p>{{ module.content|safe }}</p>      
                {% if prev_module_id %}
  
                <div class="row">
                  <div class="col">
                    <a href="{% url 'module_detail' prev_module_id %}">
                      <button type="button" class="btn btn-outline-secondary"style="background: #2d71a1; background: linear-gradient(-45deg, #1391a5, #274685); color: #fff; box-shadow: 0 10px 30px 0 rgba(0, 0, 0, 0.15);" >Prev</button>
                    </a>
                  </div>
              
              {% endif %}
  
              
              {% if next_module_id %}
              <div class="col">
              <a href="{% url 'module_detail' next_module_id %}">
                <button type="button" class="btn btn-outline-success" style="background: #2d71a1; background: linear-gradient(-45deg, #1391a5, #274685); color: #fff; box-shadow: 0 10px 30px 0 rgba(0, 0, 0, 0.15);">Next</button>
              </a>
             </div>
              {% else %}                 
                  
                  <div class="col text-end">
                      {% comment %} <a href="{% url 'quiz:main' course_id=course.id %}">Quizzes for {{ course.name }}</a>  {% endcomment %}
                      <a href="{% url 'quiz:main' %}" class="btn btn-primary" style="background: #2d71a1; background: linear-gradient(-45deg, #1391a5, #274685); color: #fff; box-shadow: 0 10px 30px 0 rgba(0, 0, 0, 0.15);">Take Quiz</a>
                  </div>
              </div>
              
              {% comment %} <a href="{% url 'quiz:main' %}" class="btn btn-primary" style="background: #2d71a1; background: linear-gradient(-45deg, #1391a5, #274685); color: #fff; box-shadow: 0 10px 30px 0 rgba(0, 0, 0, 0.15);">Take Quiz</a> {% endcomment %}
              {% endif %}
              <br>
            </div>
            </div>
          </div>
        </div>
      </div>
  </section>
</main><!-- End #main -->




{% endblock %}